<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Adds new ad groups to a specified campaign.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn277502(v=msads.100).aspx AddAdGroups Response Object
 * 
 * @uses BatchError
 * @used-by BingAdsCampaignManagementService::AddAdGroups
 */
final class AddAdGroupsResponse
{
    public $AdGroupIds;
    public $PartialErrors;
}
