<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Adds one or more ads to an ad group.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn277506(v=msads.100).aspx AddAds Request Object
 * 
 * @uses Ad
 * @used-by BingAdsCampaignManagementService::AddAds
 */
final class AddAdsRequest
{
    public $AdGroupId;
    public $Ads;
}
