<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Adds one or more campaigns to the specified account.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn277510(v=msads.100).aspx AddCampaigns Response Object
 * 
 * @uses BatchError
 * @used-by BingAdsCampaignManagementService::AddCampaigns
 */
final class AddCampaignsResponse
{
    public $CampaignIds;
    public $PartialErrors;
}
