<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the ad distribution for the ad group.
 *
 * @link http://msdn.microsoft.com/en-us/library/bb671585(v=msads.100).aspx AdDistribution Value Set
 * 
 * @used-by AdGroup
 */
final class AdDistribution
{
    /** The search network includes Bing. */
    const Search = 'Search';
    /** The content network is the ad distribution network for Bing Ads running in Windows apps. */
    const Content = 'Content';
}
