<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Adds list items such as negative keywords to the corresponding list.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn743721(v=msads.100).aspx AddListItemsToSharedList Response Object
 * 
 * @uses BatchError
 * @used-by BingAdsCampaignManagementService::AddListItemsToSharedList
 */
final class AddListItemsToSharedListResponse
{
    public $ListItemIds;
    public $PartialErrors;
}
