<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Adds the specified media to an account's media library.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn277518(v=msads.100).aspx AddMedia Request Object
 * 
 * @uses Media
 * @used-by BingAdsCampaignManagementService::AddMedia
 */
final class AddMediaRequest
{
    public $AccountId;
    public $Media;
}
