<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Adds targets to your target library.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn277526(v=msads.100).aspx AddTargetsToLibrary Response Object
 * 
 * @used-by BingAdsCampaignManagementService::AddTargetsToLibrary
 */
final class AddTargetsToLibraryResponse
{
    public $TargetIds;
}
