<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines an array of objects that associate an ad extension and its editorial status to a supported entity, for example ad group or campaign.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn250010(v=msads.100).aspx AdExtensionAssociationCollection Data Object
 * 
 * @uses AdExtensionAssociation
 * @used-by GetAdExtensionsAssociationsResponse
 */
final class AdExtensionAssociationCollection
{
    /**
     * An array of objects that associate an ad extension and its editorial status to a supported entity, for example ad group or campaign.
     *
     * @var AdExtensionAssociation[]
     */
    public $AdExtensionAssociations;
}
