<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the possible status values of an ad extension.
 *
 * @link http://msdn.microsoft.com/en-us/library/jj134386(v=msads.100).aspx AdExtensionStatus Value Set
 * 
 * @used-by AdExtension
 */
final class AdExtensionStatus
{
    /** The ad extension is active. */
    const Active = 'Active';
    /** The ad extension is deleted. */
    const Deleted = 'Deleted';
}
