<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines an object that associates an ad extension to a supported entity, for example ad group or campaign.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn249980(v=msads.100).aspx AdExtensionIdToEntityIdAssociation Data Object
 * 
 * @used-by DeleteAdExtensionsAssociationsRequest
 * @used-by GetAdExtensionsEditorialReasonsRequest
 * @used-by SetAdExtensionsAssociationsRequest
 */
final class AdExtensionIdToEntityIdAssociation
{
    /**
     * The system-generated identifier of the ad extension.
     *
     * @var int
     */
    public $AdExtensionId;
    /**
     * The identifier of an entity associated with the ad extension.
     *
     * @var int
     */
    public $EntityId;
}
