<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines a collection of ad extensions that failed editorial review.
 *
 * @link http://msdn.microsoft.com/en-us/library/jj134393(v=msads.100).aspx AdExtensionEditorialReasonCollection Data Object
 * 
 * @uses AdExtensionEditorialReason
 * @used-by GetAdExtensionsEditorialReasonsResponse
 */
final class AdExtensionEditorialReasonCollection
{
    /**
     * The identifier of the ad extension that failed editorial review.
     *
     * @var int
     */
    public $AdExtensionId;
    /**
     * A list of AdExtensionEditorialReason objects that identify the component of an ad extension that failed editorial review, and the reason for the failure.
     *
     * @var AdExtensionEditorialReason[]
     */
    public $Reasons;
}
