<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the action to apply to a BiddableAdGroupCriterion or NegativeAdGroupCriterion, specifically one that contains a ProductPartition.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn913128(v=msads.100).aspx AdGroupCriterionAction Data Object
 * 
 * @uses ItemAction
 * @uses AdGroupCriterion
 * @used-by ApplyProductPartitionActionsRequest
 */
final class AdGroupCriterionAction
{
    /**
     * The action to be applied for the AdGroupCriterion.
     *
     * @var ItemAction
     */
    public $Action;
    /**
     * The ad group criterion of either type BiddableAdGroupCriterion or NegativeAdGroupCriterion, which contains a ProductPartition and FixedBid.
     *
     * @var AdGroupCriterion
     */
    public $AdGroupCriterion;
}
