<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the possible status values of an ad.
 *
 * @link http://msdn.microsoft.com/en-us/library/cc580692(v=msads.100).aspx AdStatus Value Set
 * 
 * @used-by Ad
 */
final class AdStatus
{
    /** The ad is undergoing editorial review or has failed editorial review. */
    const Inactive = 'Inactive';
    /** The ad can be served. */
    const Active = 'Active';
    /** The ad will not serve until the owner resumes it. */
    const Paused = 'Paused';
    /** This status is for internal use only. */
    const Deleted = 'Deleted';
}
