<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the type of ad.
 *
 * @link http://msdn.microsoft.com/en-us/library/bb671537(v=msads.100).aspx AdType Value Set
 * 
 * @used-by Ad
 */
final class AdType
{
    /** The ad is a text ad. */
    const Text = 'Text';
    /** Reserved for future use. */
    const Image = 'Image';
    /** The ad is a product ad. */
    const Product = 'Product';
    /** Reserved for future use. */
    const AppInstall = 'AppInstall';
}
