<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines a specific age target range with bid adjustment.
 *
 * @link http://msdn.microsoft.com/en-us/library/bb671720(v=msads.100).aspx AgeTargetBid Data Object
 * 
 * @uses AgeRange
 * @used-by AgeTarget
 */
final class AgeTargetBid
{
    /**
     * The age range to target.
     *
     * @var AgeRange
     */
    public $Age;
    /**
     * The percent amount used to adjust the base bid.
     *
     * @var int
     */
    public $BidAdjustment;
}
