<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the values that you use to determine whether an editorial rejection is appealable.
 *
 * @link http://msdn.microsoft.com/en-us/library/jj631643(v=msads.100).aspx AppealStatus Value Set
 * 
 * @used-by EditorialReasonCollection
 */
final class AppealStatus
{
    /** The editorial rejection is appealable. */
    const Appealable = 'Appealable';
    /** The editorial rejection is appealable and an appeal has been submitted. */
    const AppealPending = 'AppealPending';
    /** The editorial rejection is not appealable. */
    const NotAppealable = 'NotAppealable';
}
