<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Appeals the editorial rejections of one or more ads or keywords that failed editorial review.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn277533(v=msads.100).aspx AppealEditorialRejections Response Object
 * 
 * @uses BatchError
 * @used-by BingAdsCampaignManagementService::AppealEditorialRejections
 */
final class AppealEditorialRejectionsResponse
{
    public $PartialErrors;
}
