<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the operating system platform and URL of the app store download webpage.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt179359(v=msads.100).aspx AppUrl Data Object
 * 
 * @used-by Ad
 * @used-by AppAdExtension
 * @used-by BiddableAdGroupCriterion
 * @used-by ImageAdExtension
 * @used-by Keyword
 * @used-by SiteLink
 */
final class AppUrl
{
    /**
     * Reserved for future use.
     *
     * @var string
     */
    public $OsType;
    /**
     * Reserved for future use.
     *
     * @var string
     */
    public $Url;
}
