<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the entity type or types associated with an ad extension.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn249973(v=msads.100).aspx AssociationType Value Set
 * 
 * @used-by AdExtensionAssociation
 * @used-by DeleteAdExtensionsAssociationsRequest
 * @used-by GetAdExtensionIdsByAccountIdRequest
 * @used-by GetAdExtensionsAssociationsRequest
 * @used-by GetAdExtensionsEditorialReasonsRequest
 * @used-by SetAdExtensionsAssociationsRequest
 */
final class AssociationType
{
    /** Specifies ad extension associations with campaigns. */
    const Campaign = 'Campaign';
    /** Specifies ad extension associations with ad groups. */
    const AdGroup = 'AdGroup';
    /** Reserved for future use. */
    const Account = 'Account';
}
