<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines a bid.
 *
 * @link http://msdn.microsoft.com/en-us/library/dd797130(v=msads.100).aspx Bid Data Object
 * 
 * @used-by AdGroup
 * @used-by FixedBid
 * @used-by Keyword
 * @used-by SitePlacement
 */
final class Bid
{
    /**
     * The bid value.
     *
     * @var float
     */
    public $Amount;
}
