<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the bidding model for an ad group.
 *
 * @link http://msdn.microsoft.com/en-us/library/dd796906(v=msads.100).aspx BiddingModel Value Set
 * 
 * @used-by AdGroup
 */
final class BiddingModel
{
    /** The ad group bidding is keyword-based. */
    const Keyword = 'Keyword';
    /** The ad group bidding is website-placement-based. */
    const SitePlacement = 'SitePlacement';
}
