<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Version 10 of the Campaign Management service is in preview.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn411606(v=msads.100).aspx BMCStore Data Object
 * 
 * @used-by GetBMCStoresByCustomerIdResponse
 */
final class BMCStore
{
    /**
     * Value will be true if the store has a catalog of items, and otherwise the value is false.
     *
     * @var bool
     */
    public $HasCatalog;
    /**
     * The unique identifier for the Bing Merchant Center store.
     *
     * @var int
     */
    public $Id;
    /**
     * Value will be true if the store is active, and otherwise the value is false.
     *
     * @var bool
     */
    public $IsActive;
    /**
     * Value will be true if the store is enabled for product ads in Bing Ads, and otherwise the value is false.
     *
     * @var bool
     */
    public $IsProductAdsEnabled;
    /**
     * Defines the name of the store as defined in the Bing Merchant Center.
     *
     * @var string
     */
    public $Name;
}
