<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the possible budget types that you can specify for a campaign.
 *
 * @link http://msdn.microsoft.com/en-us/library/bb672035(v=msads.100).aspx BudgetLimitType Value Set
 * 
 * @used-by Campaign
 */
final class BudgetLimitType
{
    /** A monthly budget that is spent until it is depleted. */
    const MonthlyBudgetSpendUntilDepleted = 'MonthlyBudgetSpendUntilDepleted';
    /** A daily budget that is spent until it is depleted. */
    const DailyBudgetAccelerated = 'DailyBudgetAccelerated';
    /** A daily budget that is spread throughout the day. */
    const DailyBudgetStandard = 'DailyBudgetStandard';
}
