<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the possible status values that indicate the progress of determining the latitude and longitude values of a business.
 *
 * @link http://msdn.microsoft.com/en-us/library/dd796820(v=msads.100).aspx BusinessGeoCodeStatus Value Set
 * 
 * @used-by LocationAdExtension
 */
final class BusinessGeoCodeStatus
{
    /** In the process of determining the latitude and longitude of the business. */
    const Pending = 'Pending';
    /** Successfully determined the latitude and longitude of the business. */
    const Complete = 'Complete';
    /** Unable to determine the latitude and longitude of the business, possibly because the address did not resolve. */
    const Invalid = 'Invalid';
    /** Unable to determine the latitude and longitude of the business. */
    const Failed = 'Failed';
}
