<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines an object that contains the negative site URLs of a campaign.
 *
 * @link http://msdn.microsoft.com/en-us/library/hh299890(v=msads.100).aspx CampaignNegativeSites Data Object
 * 
 * @used-by GetNegativeSitesByCampaignIdsResponse
 * @used-by SetNegativeSitesToCampaignsRequest
 */
final class CampaignNegativeSites
{
    /**
     * The identifier of the campaign to which the negative site URLs belong.
     *
     * @var int
     */
    public $CampaignId;
    /**
     * A list of URLs of the websites on which you do not want your ads displayed.
     *
     * @var string[]
     */
    public $NegativeSites;
}
