<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the possible status values of a campaign.
 *
 * @link http://msdn.microsoft.com/en-us/library/bb672025(v=msads.100).aspx CampaignStatus Value Set
 * 
 * @used-by Campaign
 */
final class CampaignStatus
{
    /** The campaign is active, which indicates that the campaign's ads can be served. */
    const Active = 'Active';
    /** The campaign is paused, which indicates that the campaign's ads will not serve. */
    const Paused = 'Paused';
    /** The campaign is paused, which indicates that the campaign's ads will not serve. */
    const BudgetPaused = 'BudgetPaused';
    /** The campaign is paused, which indicates that the campaign's ads will not serve. */
    const BudgetAndManualPaused = 'BudgetAndManualPaused';
    /** The campaign is deleted. */
    const Deleted = 'Deleted';
    /** Your campaign has been suspended and no ads are eligible for delivery because of potentially fraudulent activity. */
    const Suspended = 'Suspended';
}
