<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the base class of a campaign criterion.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn913126(v=msads.100).aspx CampaignCriterion Data Object
 * 
 * @uses Criterion
 * @uses KeyValuePairOfstringstring
 * @used-by AddCampaignCriterionsRequest
 * @used-by GetCampaignCriterionsByIdsResponse
 * @used-by UpdateCampaignCriterionsRequest
 */
class CampaignCriterion
{
    /**
     * Reserved for future use.
     *
     * @var int
     */
    public $BidAdjustment;
    /**
     * The identifier of the campaign to apply the criterion to.
     *
     * @var int
     */
    public $CampaignId;
    /**
     * The criterion to apply to the campaign.
     *
     * @var Criterion
     */
    public $Criterion;
    /**
     * The list of key and value strings for forward compatibility.
     *
     * @var KeyValuePairOfstringstring[]
     */
    public $ForwardCompatibilityMap;
    /**
     * The system-generated identifier that identifies this campaign criterion.
     *
     * @var int
     */
    public $Id;
    /**
     * The type of campaign criterion.
     *
     * @var string
     */
    public $Type;
}
