<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the possible campaign types.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn913129(v=msads.100).aspx CampaignType Value Set
 * 
 * @used-by Campaign
 * @used-by GetCampaignsByAccountIdRequest
 * @used-by GetCampaignsByIdsRequest
 */
final class CampaignType
{
    /** The campaign is a search and content campaign. */
    const SearchAndContent = 'SearchAndContent';
    /** The campaign is a Bing Shopping campaign. */
    const Shopping = 'Shopping';
}
