<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines a list of cities to target with bid adjustments.
 *
 * @link http://msdn.microsoft.com/en-us/library/dd796959(v=msads.100).aspx CityTarget Data Object
 * 
 * @uses CityTargetBid
 * @used-by LocationTarget
 */
final class CityTarget
{
    /**
     * An array of cities to target with bid adjustments.
     *
     * @var CityTargetBid[]
     */
    public $Bids;
}
