<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines a list of countries or regions to target with bid adjustments.
 *
 * @link http://msdn.microsoft.com/en-us/library/bb671605(v=msads.100).aspx CountryTarget Data Object
 * 
 * @uses CountryTargetBid
 * @used-by LocationTarget
 */
final class CountryTarget
{
    /**
     * An array of countries or regions to target with bid adjustments.
     *
     * @var CountryTargetBid[]
     */
    public $Bids;
}
