<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the base object of a criterion.
 *
 * @link http://msdn.microsoft.com/en-us/library/jj738613(v=msads.100).aspx Criterion Data Object
 * 
 * @used-by AdGroupCriterion
 * @used-by CampaignCriterion
 */
class Criterion
{
    /**
     * The type of criterion.
     *
     * @var string
     */
    public $Type;
}
