<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Represents a date.
 *
 * @link http://msdn.microsoft.com/en-us/library/bb671903(v=msads.100).aspx Date Data Object
 * 
 * @used-by AdGroup
 */
final class Date
{
    /**
     * Specifies the day of the month.
     *
     * @var int
     */
    public $Day;
    /**
     * Specifies the month.
     *
     * @var int
     */
    public $Month;
    /**
     * Specifies the year.
     *
     * @var int
     */
    public $Year;
}
