<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Deletes one or more campaigns in a specified account.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn236314(v=msads.100).aspx DeleteCampaigns Request Object
 * 
 * @used-by BingAdsCampaignManagementService::DeleteCampaigns
 */
final class DeleteCampaignsRequest
{
    public $AccountId;
    public $CampaignIds;
}
