<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Deletes one or more website-placement bids from an ad group.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn236315(v=msads.100).aspx DeleteSitePlacements Response Object
 * 
 * @used-by BingAdsCampaignManagementService::DeleteSitePlacements
 */
final class DeleteSitePlacementsResponse
{
}
