<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Deletes negative keywords from the specified campaign or ad group.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn743725(v=msads.100).aspx DeleteNegativeKeywordsFromEntities Request Object
 * 
 * @uses EntityNegativeKeyword
 * @used-by BingAdsCampaignManagementService::DeleteNegativeKeywordsFromEntities
 */
final class DeleteNegativeKeywordsFromEntitiesRequest
{
    public $EntityNegativeKeywords;
}
