<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Removes the target association for the specified campaign.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn277503(v=msads.100).aspx DeleteTargetFromCampaign Response Object
 * 
 * @used-by BingAdsCampaignManagementService::DeleteTargetFromCampaign
 */
final class DeleteTargetFromCampaignResponse
{
}
