<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Deletes one or more ads in a specified ad group.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn236310(v=msads.100).aspx DeleteAds Response Object
 * 
 * @uses BatchError
 * @used-by BingAdsCampaignManagementService::DeleteAds
 */
final class DeleteAdsResponse
{
    public $PartialErrors;
}
