<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines a specific device target with bid adjustment.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn249988(v=msads.100).aspx DeviceOSTargetBid Data Object
 * 
 * @used-by DeviceOSTarget
 */
final class DeviceOSTargetBid
{
    /**
     * The percent amount by which to adjust the base bid for the specified device target.
     *
     * @var int
     */
    public $BidAdjustment;
    /**
     * The name of the device to target.
     *
     * @var string
     */
    public $DeviceName;
    /**
     * This element is deprecated and will be sunset in a future version of the API.
     *
     * @var string[]
     */
    public $OSNames;
}
