<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines dimension information for media on a website.
 *
 * @link http://msdn.microsoft.com/en-us/library/dd796881(v=msads.100).aspx Dimension Data Object
 * 
 * @used-by MediaType
 */
final class Dimension
{
    /**
     * The height.
     *
     * @var int
     */
    public $Height;
    /**
     * The width.
     *
     * @var int
     */
    public $Width;
}
