<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines a collection of ads or keywords that failed editorial review, and the reason for the failure.
 *
 * @link http://msdn.microsoft.com/en-us/library/ff728504(v=msads.100).aspx EditorialReasonCollection Data Object
 * 
 * @uses AppealStatus
 * @uses EditorialReason
 * @used-by GetEditorialReasonsByIdsResponse
 */
final class EditorialReasonCollection
{
    /**
     * Identifies the ad group which is the parent of the ad or keyword that failed editorial review.
     *
     * @var int
     */
    public $AdGroupId;
    /**
     * Identifies the ad or keyword that failed editorial review.
     *
     * @var int
     */
    public $AdOrKeywordId;
    /**
     * A value that determines whether you can appeal the issues found by the editorial review.
     *
     * @var AppealStatus
     */
    public $AppealStatus;
    /**
     * An array of editorial reasons that you can use to determine the component of an ad or keyword that failed editorial review, and the reason for the failure.
     *
     * @var EditorialReason[]
     */
    public $Reasons;
}
