<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the possible types of entities.
 *
 * @link http://msdn.microsoft.com/en-us/library/jj622172(v=msads.100).aspx EntityType Value Set
 * 
 * @used-by AppealEditorialRejectionsRequest
 * @used-by GetEditorialReasonsByIdsRequest
 */
final class EntityType
{
    /** The entity is a Campaign object. */
    const Campaign = 'Campaign';
    /** The entity is an AdGroup object. */
    const AdGroup = 'AdGroup';
    /** The entity is a Target object. */
    const Target = 'Target';
    /** The entity is an Ad object or an object that derives from it, such as the TextAd object. */
    const Ad = 'Ad';
    /** The entity is a Keyword object. */
    const Keyword = 'Keyword';
    /** For future use. */
    const AdExtension = 'AdExtension';
    const AdGroupCriterion = 'AdGroupCriterion';
}
