<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines an object that contains a set of negative keywords that are only associated with the corresponding entity such as a campaign or ad group.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn743733(v=msads.100).aspx EntityNegativeKeyword Data Object
 * 
 * @uses NegativeKeyword
 * @used-by AddNegativeKeywordsToEntitiesRequest
 * @used-by DeleteNegativeKeywordsFromEntitiesRequest
 * @used-by GetNegativeKeywordsByEntityIdsResponse
 */
final class EntityNegativeKeyword
{
    /**
     * The system-generated identifier of a campaign or ad group that is associated with the negative keywords.
     *
     * @var int
     */
    public $EntityId;
    /**
     * The type of entity such as a campaign that is associated with the negative keywords.
     *
     * @var string
     */
    public $EntityType;
    /**
     * An array of negative keywords that are associated with the corresponding campaign or ad group.
     *
     * @var NegativeKeyword[]
     */
    public $NegativeKeywords;
}
