<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines an object that contains the unique system identifier of an entity such as ad or keyword, and the identifier of its parent.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt179358(v=msads.100).aspx EntityIdToParentIdAssociation Data Object
 * 
 * @used-by AppealEditorialRejectionsRequest
 * @used-by GetEditorialReasonsByIdsRequest
 */
final class EntityIdToParentIdAssociation
{
    /**
     * The system-generated unique identifier of an entity such as ad or keyword.
     *
     * @var int
     */
    public $EntityId;
    /**
     * The identifier of the entity's parent.
     *
     * @var int
     */
    public $ParentId;
}
