<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines a specific gender target with bid adjustment.
 *
 * @link http://msdn.microsoft.com/en-us/library/bb671554(v=msads.100).aspx GenderTargetBid Data Object
 * 
 * @uses GenderType
 * @used-by GenderTarget
 */
final class GenderTargetBid
{
    /**
     * The percent amount by which to adjust the base bid.
     *
     * @var int
     */
    public $BidAdjustment;
    /**
     * The gender to target.
     *
     * @var GenderType
     */
    public $Gender;
}
