<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the genders that are available for ad group or campaign targeting.
 *
 * @link http://msdn.microsoft.com/en-us/library/bb671519(v=msads.100).aspx GenderType Value Set
 * 
 * @used-by GenderTargetBid
 */
final class GenderType
{
    const Male = 'Male';
    const Female = 'Female';
}
