<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines a list of genders to target with bid adjustments.
 *
 * @link http://msdn.microsoft.com/en-us/library/bb671655(v=msads.100).aspx GenderTarget Data Object
 * 
 * @uses GenderTargetBid
 * @used-by Target
 */
final class GenderTarget
{
    /**
     * An array of genders to target with bid adjustments.
     *
     * @var GenderTargetBid[]
     */
    public $Bids;
}
