<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Gets the specified criterions.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn277520(v=msads.100).aspx GetAdGroupCriterionsByIds Request Object
 * 
 * @uses CriterionType
 * @used-by BingAdsCampaignManagementService::GetAdGroupCriterionsByIds
 */
final class GetAdGroupCriterionsByIdsRequest
{
    public $AccountId;
    public $AdGroupCriterionIds;
    public $AdGroupId;
    public $CriterionType;
}
