<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Gets editorial rejection reasons for the respective ad extension and entity associations.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn236313(v=msads.100).aspx GetAdExtensionsEditorialReasons Request Object
 * 
 * @uses AdExtensionIdToEntityIdAssociation
 * @uses AssociationType
 * @used-by BingAdsCampaignManagementService::GetAdExtensionsEditorialReasons
 */
final class GetAdExtensionsEditorialReasonsRequest
{
    public $AccountId;
    public $AdExtensionIdToEntityIdAssociations;
    public $AssociationType;
}
