<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Retrieves the ads that are associated with an ad group.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn277534(v=msads.100).aspx GetAdsByAdGroupId Request Object
 * 
 * @used-by BingAdsCampaignManagementService::GetAdsByAdGroupId
 */
final class GetAdsByAdGroupIdRequest
{
    public $AdGroupId;
}
