<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Gets the Bing Merchant Center stores for the specified customer.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn411607(v=msads.100).aspx GetBMCStoresByCustomerId Request Object
 * 
 * @used-by BingAdsCampaignManagementService::GetBMCStoresByCustomerId
 */
final class GetBMCStoresByCustomerIdRequest
{
}
