<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Retrieves all the campaigns that exist within a specified account.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn236299(v=msads.100).aspx GetCampaignsByAccountId Response Object
 * 
 * @uses Campaign
 * @used-by BingAdsCampaignManagementService::GetCampaignsByAccountId
 */
final class GetCampaignsByAccountIdResponse
{
    public $Campaigns;
}
