<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Retrieves the keywords for an ad group.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn236311(v=msads.100).aspx GetKeywordsByAdGroupId Response Object
 * 
 * @uses Keyword
 * @used-by BingAdsCampaignManagementService::GetKeywordsByAdGroupId
 */
final class GetKeywordsByAdGroupIdResponse
{
    public $Keywords;
}
