<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Gets the list items such as the negative keywords of a negative keyword list.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn743729(v=msads.100).aspx GetListItemsBySharedList Request Object
 * 
 * @uses SharedList
 * @used-by BingAdsCampaignManagementService::GetListItemsBySharedList
 */
final class GetListItemsBySharedListRequest
{
    public $SharedList;
}
