<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Gets the media associations of the specified entity type from an account's media library.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn798359(v=msads.100).aspx GetMediaAssociations Request Object
 * 
 * @uses MediaEnabledEntityFilter
 * @used-by BingAdsCampaignManagementService::GetMediaAssociations
 */
final class GetMediaAssociationsRequest
{
    public $MediaEnabledEntities;
    public $MediaIds;
}
