<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Gets the negative site URLs of the specified campaigns.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn277525(v=msads.100).aspx GetNegativeSitesByCampaignIds Response Object
 * 
 * @uses CampaignNegativeSites
 * @uses BatchError
 * @used-by BingAdsCampaignManagementService::GetNegativeSitesByCampaignIds
 */
final class GetNegativeSitesByCampaignIdsResponse
{
    public $CampaignNegativeSites;
    public $PartialErrors;
}
