<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Retrieves detailed information about the specified targets.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn236304(v=msads.100).aspx GetTargetsByIds Response Object
 * 
 * @uses Target
 * @used-by BingAdsCampaignManagementService::GetTargetsByIds
 */
final class GetTargetsByIdsResponse
{
    public $Targets;
}
