<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Retrieves detailed information about the targets that are associated with the specified campaigns.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn236300(v=msads.100).aspx GetTargetsByCampaignIds Request Object
 * 
 * @used-by BingAdsCampaignManagementService::GetTargetsByCampaignIds
 */
final class GetTargetsByCampaignIdsRequest
{
    public $CampaignIds;
}
