<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines an image media representation with height and width.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn766197(v=msads.100).aspx ImageMediaRepresentation Data Object
 */
final class ImageMediaRepresentation extends MediaRepresentation
{
    /**
     * The height of the image in pixels.
     *
     * @var int
     */
    public $Height;
    /**
     * The width of the image in pixels.
     *
     * @var int
     */
    public $Width;
}
