<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the editorial review status values of a keyword.
 *
 * @link http://msdn.microsoft.com/en-us/library/cc565085(v=msads.100).aspx KeywordEditorialStatus Value Set
 * 
 * @used-by Keyword
 * @used-by GetKeywordsByEditorialStatusRequest
 */
final class KeywordEditorialStatus
{
    /** The keyword passed editorial review. */
    const Active = 'Active';
    /** The keyword failed editorial review. */
    const Disapproved = 'Disapproved';
    /** One or more elements of the keyword is undergoing editorial review. */
    const Inactive = 'Inactive';
    /** The keyword passed editorial review in one or more markets, and one or more elements of the keyword is undergoing editorial review in another market. */
    const ActiveLimited = 'ActiveLimited';
}
