<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the possible status values of a keyword.
 *
 * @link http://msdn.microsoft.com/en-us/library/bb671482(v=msads.100).aspx KeywordStatus Value Set
 * 
 * @used-by Keyword
 */
final class KeywordStatus
{
    /** The keyword can be used to match user search queries. */
    const Active = 'Active';
    /** The keyword cannot be used to match user search queries until the owner resumes it. */
    const Paused = 'Paused';
    /** This status is for internal use only. */
    const Deleted = 'Deleted';
    /** The keyword is undergoing editorial review or has failed editorial review. */
    const Inactive = 'Inactive';
}
