<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the possible match types for a keyword bid.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn249974(v=msads.100).aspx MatchType Value Set
 * 
 * @used-by Keyword
 * @used-by NegativeKeyword
 */
final class MatchType
{
    /** The keyword match type is Exact. */
    const Exact = 'Exact';
    /** The keyword match type is Phrase. */
    const Phrase = 'Phrase';
    /** The keyword match type is Broad. */
    const Broad = 'Broad';
    /** The keyword match type is Content. */
    const Content = 'Content';
}
