<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines a media representation base class that includes a media download Url.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn766194(v=msads.100).aspx MediaRepresentation Data Object
 * 
 * @used-by MediaMetaData
 */
class MediaRepresentation
{
    /**
     * The name of the media representation.
     *
     * @var string
     */
    public $Name;
    /**
     * The type of the media representation, for example ImageMediaRepresentation.
     *
     * @var string
     */
    public $Type;
    /**
     * The media download URL.
     *
     * @var string
     */
    public $Url;
}
