<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines media type information for a website.
 *
 * @link http://msdn.microsoft.com/en-us/library/dd797128(v=msads.100).aspx MediaType Data Object
 * 
 * @uses Dimension
 * @used-by PlacementDetail
 */
final class MediaType
{
    /**
     * The media dimensions.
     *
     * @var Dimension[]
     */
    public $Dimensions;
    /**
     * The name of the media type.
     *
     * @var string
     */
    public $Name;
}
