<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines a media meta data object.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn766198(v=msads.100).aspx MediaMetaData Data Object
 * 
 * @uses MediaRepresentation
 * @used-by GetMediaMetaDataByAccountIdResponse
 * @used-by GetMediaMetaDataByIdsResponse
 */
final class MediaMetaData
{
    /**
     * The system identifier of the media meta data.
     *
     * @var int
     */
    public $Id;
    /**
     * The name of the media subclass.
     *
     * @var string
     */
    public $MediaType;
    /**
     * An array of MediaRepresentation-derived objects, for example ImageMediaRepresentation, that each include download Urls for one or more media representations.
     *
     * @var MediaRepresentation[]
     */
    public $Representations;
    /**
     * The type of media in the library.
     *
     * @var string
     */
    public $Type;
}
