<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines a list of metro area targets with bid adjustments.
 *
 * @link http://msdn.microsoft.com/en-us/library/bb671815(v=msads.100).aspx MetroAreaTarget Data Object
 * 
 * @uses MetroAreaTargetBid
 * @used-by LocationTarget
 */
final class MetroAreaTarget
{
    /**
     * An array of MetroAreaTargetBid objects that specifies the metropolitan areas to target and the incremental bid percentages to apply to the base bid.
     *
     * @var MetroAreaTargetBid[]
     */
    public $Bids;
}
