<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines a negative ad group criterion that can be used to abstain from bidding on the Bing Shopping products in this ad group.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn913133(v=msads.100).aspx NegativeAdGroupCriterion Data Object
 */
final class NegativeAdGroupCriterion extends AdGroupCriterion
{
}
