<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the possible search networks on which an ad can display.
 *
 * @link http://msdn.microsoft.com/en-us/library/ff986253(v=msads.100).aspx Network Value Set
 * 
 * @used-by AdGroup
 */
final class Network
{
    /** Display ads on owned and operated networks, as well as syndicated search networks. */
    const OwnedAndOperatedAndSyndicatedSearch = 'OwnedAndOperatedAndSyndicatedSearch';
    /** Display ads on only owned and operated networks. */
    const OwnedAndOperatedOnly = 'OwnedAndOperatedOnly';
    /** Display ads on only syndicated search networks. */
    const SyndicatedSearchOnly = 'SyndicatedSearchOnly';
}
