<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the size and type of media that the publisher website supports for ad placements.
 *
 * @link http://msdn.microsoft.com/en-us/library/dd796936(v=msads.100).aspx PlacementDetail Data Object
 * 
 * @uses ImpressionsPerDayRange
 * @uses MediaType
 * @used-by GetPlacementDetailsForUrlsResponse
 */
final class PlacementDetail
{
    /**
     * Not supported.
     *
     * @var ImpressionsPerDayRange
     */
    public $ImpressionsRangePerDay;
    /**
     * The URL of the publisher's website.
     *
     * @var string
     */
    public $PathName;
    /**
     * The identifier of the publisher.
     *
     * @var int
     */
    public $PlacementId;
    /**
     * An array of MediaType objects that contains the size and type of media that the publisher website supports.
     *
     * @var MediaType[]
     */
    public $SupportedMediaTypes;
}
