<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the pricing model for an ad group.
 *
 * @link http://msdn.microsoft.com/en-us/library/cc580680(v=msads.100).aspx PricingModel Value Set
 * 
 * @used-by AdGroup
 */
final class PricingModel
{
    /** The pricing model is cost-per-click (CPC). */
    const Cpc = 'Cpc';
    /** The pricing model is cost per thousand-impressions (CPM). */
    const Cpm = 'Cpm';
}
