<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines an ad group level product partition with one condition that helps determine whether a product from the Bing Merchant Center store gets served as a product ad.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn913123(v=msads.100).aspx ProductPartition Data Object
 * 
 * @uses ProductCondition
 * @uses ProductPartitionType
 */
final class ProductPartition extends Criterion
{
    /**
     * A condition that helps determine whether a product from the Bing Merchant Center store gets served as an ad.
     *
     * @var ProductCondition
     */
    public $Condition;
    /**
     * The identifier of the parent BiddableAdGroupCriterion or NegativeAdGroupCriterion.
     *
     * @var int
     */
    public $ParentCriterionId;
    /**
     * The type of product partition, for example Subdivision or Unit.
     *
     * @var ProductPartitionType
     */
    public $PartitionType;
}
