<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the possible types of product partitions.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn913120(v=msads.100).aspx ProductPartitionType Value Set
 * 
 * @used-by ProductPartition
 */
final class ProductPartitionType
{
    /** The ProductPartition is a product group subdivision. */
    const Subdivision = 'Subdivision';
    /** The ProductPartition is a product group unit. */
    const Unit = 'Unit';
}
