<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines a campaign level product scope with list of conditions that help determine whether a product from the Bing Merchant Center store gets served as a product ad.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn913124(v=msads.100).aspx ProductScope Data Object
 * 
 * @uses ProductCondition
 */
final class ProductScope extends Criterion
{
    /**
     * A list of up to 7 product conditions that helps determine whether a product from the Bing Merchant Center store gets served as an ad.
     *
     * @var ProductCondition[]
     */
    public $Conditions;
}
