<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines a list of geographical radius targets with bid adjustments.
 *
 * @link http://msdn.microsoft.com/en-us/library/dd796953(v=msads.100).aspx RadiusTarget Data Object
 * 
 * @uses RadiusTargetBid
 * @used-by LocationTarget
 */
final class RadiusTarget
{
    /**
     * An array of RadiusTargetBid objects that specifies an area surrounding a geographical location to target and the incremental bid percentages to apply to the base bid.
     *
     * @var RadiusTargetBid[]
     */
    public $Bids;
}
