<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Sets the negative site URLs of the specified ad groups.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn236317(v=msads.100).aspx SetNegativeSitesToAdGroups Response Object
 * 
 * @uses BatchError
 * @used-by BingAdsCampaignManagementService::SetNegativeSitesToAdGroups
 */
final class SetNegativeSitesToAdGroupsResponse
{
    public $PartialErrors;
}
