<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Associates the specified target with the specified ad group.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn277508(v=msads.100).aspx SetTargetToAdGroup Request Object
 * 
 * @used-by BingAdsCampaignManagementService::SetTargetToAdGroup
 */
final class SetTargetToAdGroupRequest
{
    public $AdGroupId;
    public $TargetId;
    public $ReplaceAssociation;
}
