<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the base class of a setting.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn913122(v=msads.100).aspx Setting Data Object
 * 
 * @used-by AdGroup
 * @used-by Campaign
 */
class Setting
{
    /**
     * The type of setting.
     *
     * @var string
     */
    public $Type;
}
