<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the base class of a shared list.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn743734(v=msads.100).aspx SharedList Data Object
 * 
 * @used-by AddListItemsToSharedListRequest
 * @used-by DeleteListItemsFromSharedListRequest
 * @used-by GetListItemsBySharedListRequest
 */
class SharedList extends SharedEntity
{
    /**
     * The number of SharedListItem objects that are added to this shared list.
     *
     * @var int
     */
    public $ItemCount;
}
