<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the base class of a shared entity.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn743735(v=msads.100).aspx SharedEntity Data Object
 * 
 * @uses KeyValuePairOfstringstring
 * @used-by AddSharedEntityRequest
 * @used-by DeleteSharedEntitiesRequest
 * @used-by GetSharedEntitiesByAccountIdResponse
 * @used-by UpdateSharedEntitiesRequest
 */
class SharedEntity
{
    /**
     * The number of active associations between this object and an entity such as a campaign.
     *
     * @var int
     */
    public $AssociationCount;
    /**
     * The list of key and value strings for forward compatibility.
     *
     * @var KeyValuePairOfstringstring[]
     */
    public $ForwardCompatibilityMap;
    /**
     * The system-generated identifier of the shared entity.
     *
     * @var int
     */
    public $Id;
    /**
     * The name of the shared entity.
     *
     * @var string
     */
    public $Name;
    /**
     * The type of the shared entity.
     *
     * @var string
     */
    public $Type;
}
