<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines the base class of a shared list item.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn743738(v=msads.100).aspx SharedListItem Data Object
 * 
 * @uses KeyValuePairOfstringstring
 * @used-by AddListItemsToSharedListRequest
 * @used-by AddSharedEntityRequest
 * @used-by GetListItemsBySharedListResponse
 */
class SharedListItem
{
    /**
     * The list of key and value strings for forward compatibility.
     *
     * @var KeyValuePairOfstringstring[]
     */
    public $ForwardCompatibilityMap;
    /**
     * The type of the shared list item.
     *
     * @var string
     */
    public $Type;
}
