<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines an ad extension that specifies one or more site links to add to a text ad.
 *
 * @link http://msdn.microsoft.com/en-us/library/jj134387(v=msads.100).aspx SiteLinksAdExtension Data Object
 * 
 * @uses SiteLink
 */
final class SiteLinksAdExtension extends AdExtension
{
    /**
     * A list of site links.
     *
     * @var SiteLink[]
     */
    public $SiteLinks;
}
