<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines a list of state targets with bid adjustments.
 *
 * @link http://msdn.microsoft.com/en-us/library/dd796793(v=msads.100).aspx StateTarget Data Object
 * 
 * @uses StateTargetBid
 * @used-by LocationTarget
 */
final class StateTarget
{
    /**
     * An array of StateTargetBid objects that specifies the states/provinces/territories to target and the incremental bid percentages to apply to the base bid.
     *
     * @var StateTargetBid[]
     */
    public $Bids;
}
