<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Defines information about a target in your library.
 *
 * @link http://msdn.microsoft.com/en-us/library/dd796878(v=msads.100).aspx TargetInfo Data Object
 * 
 * @used-by GetTargetsInfoFromLibraryResponse
 */
final class TargetInfo
{
    /**
     * The identifier of the target.
     *
     * @var int
     */
    public $Id;
    /**
     * The name of the target.
     *
     * @var string
     */
    public $Name;
}
