<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Updates specified campaigns in a specified account.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn277536(v=msads.100).aspx UpdateCampaigns Request Object
 * 
 * @uses Campaign
 * @used-by BingAdsCampaignManagementService::UpdateCampaigns
 */
final class UpdateCampaignsRequest
{
    public $AccountId;
    public $Campaigns;
}
