<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Updates one or more website-placement bids in an ad group.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn236298(v=msads.100).aspx UpdateSitePlacements Response Object
 * 
 * @used-by BingAdsCampaignManagementService::UpdateSitePlacements
 */
final class UpdateSitePlacementsResponse
{
}
