<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\CampaignManagement;

/**
 * Updates targets in your target library.
 *
 * @link http://msdn.microsoft.com/en-us/library/dn236301(v=msads.100).aspx UpdateTargetsInLibrary Request Object
 * 
 * @uses Target
 * @used-by BingAdsCampaignManagementService::UpdateTargetsInLibrary
 */
final class UpdateTargetsInLibraryRequest
{
    public $Targets;
}
