<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\Bulk;

/**
 * Defines an object that identifies a campaign to download.
 *
 * @link http://msdn.microsoft.com/en-us/library/jj134990(v=msads.100).aspx CampaignScope Data Object
 * 
 * @used-by DownloadCampaignsByCampaignIdsRequest
 */
final class CampaignScope
{
    /**
     * The identifier of the campaign to download.
     *
     * @var int
     */
    public $CampaignId;
    /**
     * The identifier of the account that owns the campaign to download.
     *
     * @var int
     */
    public $ParentAccountId;
}
