<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\Bulk;

/**
 * Downloads an account's campaign data.
 *
 * @link http://msdn.microsoft.com/en-us/library/jj885755(v=msads.100).aspx DownloadCampaignsByAccountIds Response Object
 * 
 * @used-by BingAdsBulkService::DownloadCampaignsByAccountIds
 */
final class DownloadCampaignsByAccountIdsResponse
{
    public $DownloadRequestId;
}
