<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\Bulk;

/**
 * Defines the file formats for a download request.
 *
 * @link http://msdn.microsoft.com/en-us/library/jj919219(v=msads.100).aspx DownloadFileType Value Set
 * 
 * @used-by DownloadCampaignsByAccountIdsRequest
 * @used-by DownloadCampaignsByCampaignIdsRequest
 */
final class DownloadFileType
{
    /** The file format is comma separated values (CSV). */
    const Csv = 'Csv';
    /** The file format is tab separated values (TSV). */
    const Tsv = 'Tsv';
}
