<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\Bulk;

/**
 * Downloads the specified campaigns' data.
 *
 * @link http://msdn.microsoft.com/en-us/library/jj885756(v=msads.100).aspx DownloadCampaignsByCampaignIds Request Object
 * 
 * @uses CampaignScope
 * @uses CompressionType
 * @uses DataScope
 * @uses DownloadFileType
 * @uses BulkDownloadEntity
 * @uses PerformanceStatsDateRange
 * @used-by BingAdsBulkService::DownloadCampaignsByCampaignIds
 */
final class DownloadCampaignsByCampaignIdsRequest
{
    public $Campaigns;
    public $CompressionType;
    public $DataScope;
    public $DownloadFileType;
    public $Entities;
    public $FormatVersion;
    public $LastSyncTimeInUTC;
    public $PerformanceStatsDateRange;
}
