<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * Defines a fault object that operations return when generic errors occur, such as an authentication error.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219306(v=msads.100).aspx AdApiFaultDetail Data Object
 * 
 * @uses AdApiError
 */
final class AdApiFaultDetail extends ApplicationFault
{
    /**
     * An array of AdApiError objects that contains the details that explain why the service operation failed.
     *
     * @var AdApiError[]
     */
    public $Errors;
}
