<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * Defines the possible values that indicate whether all or a subset of an ad group's existing keywords are used to determine the bid landscape.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219323(v=msads.100).aspx AdGroupBidLandscapeType Value Set
 * 
 * @used-by AdGroupBidLandscape
 * @used-by AdGroupBidLandscapeInput
 */
final class AdGroupBidLandscapeType
{
    /** All of an ad group's existing keywords are used to determine the bid landscape. */
    const Uniform = 'Uniform';
    /** Only existing keywords that use the ad group's default bid are used to determine the bid landscape. */
    const DefaultBidOnly = 'DefaultBidOnly';
}
