<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * Defines the possible bid opportunity types you can request when calling GetBidOpportunities.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219343(v=msads.100).aspx BidOpportunityType Value Set
 * 
 * @used-by GetBidOpportunitiesRequest
 */
final class BidOpportunityType
{
    /** The bid opportunity may lead to ads shown in one of the first page positions of search results. */
    const FirstPage = 'FirstPage';
    /** The bid opportunity may lead to ads shown in one of the mainline positions of search results. */
    const MainLine = 'MainLine';
    /** The bid opportunity may lead to ads shown in the first mainline position of search results. */
    const MainLine1 = 'MainLine1';
}
