<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

final class Field
{
    const UNKNOW = 'UNKNOW';
    const BidLandscape = 'BidLandscape';
    const BidSuggestion = 'BidSuggestion';
    const EntityAuctionInsight = 'EntityAuctionInsight';
    const AggregatedAuctionInsight = 'AggregatedAuctionInsight';
    const AuctionInsightAvailableChildren = 'AuctionInsightAvailableChildren';
    const TopMover = 'TopMover';
    const AccountId = 'AccountId';
    const CampaignId = 'CampaignId';
    const AdGroupId = 'AdGroupId';
    const KeywordId = 'KeywordId';
    const TimeInterval = 'TimeInterval';
}
