<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * Given a list of existing keywords, this operation returns for each a list of suggested bids and estimated performance statistics.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219285(v=msads.100).aspx GetBidLandscapeByKeywordIds Response Object
 * 
 * @uses KeywordBidLandscape
 * @used-by BingAdsAdInsightService::GetBidLandscapeByKeywordIds
 */
final class GetBidLandscapeByKeywordIdsResponse
{
    public $BidLandscape;
}
