<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * Gets the campaign budget opportunities of the specified campaign.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219289(v=msads.100).aspx GetBudgetOpportunities Request Object
 * 
 * @used-by BingAdsAdInsightService::GetBudgetOpportunities
 */
final class GetBudgetOpportunitiesRequest
{
    public $CampaignId;
}
