<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * Gets the estimated bid value of one or more keywords that could result in an ad appearing in the targeted position in the search results.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219297(v=msads.100).aspx GetEstimatedBidByKeywords Request Object
 * 
 * @uses KeywordAndMatchType
 * @uses TargetAdPosition
 * @uses Currency
 * @used-by BingAdsAdInsightService::GetEstimatedBidByKeywords
 */
final class GetEstimatedBidByKeywordsRequest
{
    public $Keywords;
    public $TargetPositionForAds;
    public $Language;
    public $PublisherCountries;
    public $Currency;
    public $CampaignId;
    public $AdGroupId;
    public $EntityLevelBid;
}
