<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * Gets the number of times the normalized term was used in a search during the specified time period.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219308(v=msads.100).aspx GetHistoricalSearchCount Response Object
 * 
 * @uses KeywordSearchCount
 * @used-by BingAdsAdInsightService::GetHistoricalSearchCount
 */
final class GetHistoricalSearchCountResponse
{
    public $KeywordSearchCounts;
}
