<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * Gets the historical performance of the normalized search term.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219302(v=msads.100).aspx GetHistoricalKeywordPerformance Response Object
 * 
 * @uses KeywordHistoricalPerformance
 * @used-by BingAdsAdInsightService::GetHistoricalKeywordPerformance
 */
final class GetHistoricalKeywordPerformanceResponse
{
    public $KeywordHistoricalPerformances;
}
