<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * Gets the geographical locations of users who have searched for the specified keywords.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219328(v=msads.100).aspx GetKeywordLocations Response Object
 * 
 * @uses KeywordLocationResult
 * @used-by BingAdsAdInsightService::GetKeywordLocations
 */
final class GetKeywordLocationsResponse
{
    public $KeywordLocationResult;
}
