<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * Gets the age and gender of users who have searched for the specified keywords.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219307(v=msads.100).aspx GetKeywordDemographics Request Object
 * 
 * @used-by BingAdsAdInsightService::GetKeywordDemographics
 */
final class GetKeywordDemographicsRequest
{
    public $Keywords;
    public $Language;
    public $PublisherCountry;
    public $Device;
}
