<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * Gets a list of keyword suggestions that are relevant to the specified ad group.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219321(v=msads.100).aspx GetKeywordOpportunities Request Object
 * 
 * @uses KeywordOpportunityType
 * @used-by BingAdsAdInsightService::GetKeywordOpportunities
 */
final class GetKeywordOpportunitiesRequest
{
    public $AdGroupId;
    public $CampaignId;
    public $OpportunityType;
}
