<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * Defines an object that contains the number of times that the keyword was used in a search query during the specified time period.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219325(v=msads.100).aspx HistoricalSearchCountPeriodic Data Object
 * 
 * @uses DayMonthAndYear
 * @used-by SearchCountsByAttributes
 */
final class HistoricalSearchCountPeriodic
{
    /**
     * The number of times that the keyword was used in a search query on the specified device type during the time period.
     *
     * @var int
     */
    public $SearchCount;
    /**
     * The time period in which the count was captured.
     *
     * @var DayMonthAndYear
     */
    public $DayMonthAndYear;
}
