<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * Defines an object that contains the keyword and the estimated bid value for each match type.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219290(v=msads.100).aspx KeywordEstimatedBid Data Object
 * 
 * @uses EstimatedBidAndTraffic
 * @used-by KeywordIdEstimatedBid
 * @used-by GetEstimatedBidByKeywordsResponse
 */
final class KeywordEstimatedBid
{
    /**
     * The keyword to which the estimates apply.
     *
     * @var string
     */
    public $Keyword;
    /**
     * A list of EstimatedBidAndTraffic objects that contains the suggested bid value for the keyword and match type.
     *
     * @var EstimatedBidAndTraffic[]
     */
    public $EstimatedBids;
}
