<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * Defines an object that contains a list of suggested keywords that may perform better than the specified keyword.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219313(v=msads.100).aspx KeywordSuggestion Data Object
 * 
 * @uses KeywordAndConfidence
 * @used-by SuggestKeywordsFromExistingKeywordsResponse
 */
final class KeywordSuggestion
{
    /**
     * The keyword to which the suggested keywords apply.
     *
     * @var string
     */
    public $Keyword;
    /**
     * A KeywordAndConfidence array that contains a list of suggested keywords and, for each keyword, a score that indicates the probability that using the keyword would result in an ad being included in the results of a search query.
     *
     * @var KeywordAndConfidence[]
     */
    public $SuggestionsAndConfidence;
}
