<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * Defines an object that contains the keyword and percentage of users by age and gender (if known) who searched for the specified keyword.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219288(v=msads.100).aspx KeywordDemographicResult Data Object
 * 
 * @uses KeywordDemographic
 * @used-by GetKeywordDemographicsResponse
 */
final class KeywordDemographicResult
{
    /**
     * The keyword.
     *
     * @var string
     */
    public $Keyword;
    /**
     * An array of KeywordDemographic objects that contains the percentage of users by age and gender (if known) that searched for the keyword on the device.
     *
     * @var KeywordDemographic[]
     */
    public $KeywordDemographics;
}
