<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * Defines the possible keyword opportunity types you can request when calling GetKeywordOpportunities.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219346(v=msads.100).aspx KeywordOpportunityType Value Set
 * 
 * @used-by GetKeywordOpportunitiesRequest
 */
final class KeywordOpportunityType
{
    /** The keyword opportunity will be suggested based on the marketplace impact of adding keywords with the broad match type. */
    const BroadMatch = 'BroadMatch';
    /** The keyword opportunity will be suggested based on the full context of the campaign, including existing keywords, landing page, and ad copy. */
    const CampaignContext = 'CampaignContext';
}
