<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * Defines an object that contains the identifier of a keyword and the estimated search results position for the keyword and match type.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219296(v=msads.100).aspx KeywordIdEstimatedPosition Data Object
 * 
 * @uses KeywordEstimatedPosition
 * @used-by GetEstimatedPositionByKeywordIdsResponse
 */
final class KeywordIdEstimatedPosition
{
    /**
     * The identifier of the keyword to which the estimated position applies.
     *
     * @var int
     */
    public $KeywordId;
    /**
     * An object that contains the keyword string and estimated position in the search results given the specified maximum bid.
     *
     * @var KeywordEstimatedPosition
     */
    public $KeywordEstimatedPosition;
}
