<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * Defines an object that contains a list of estimated clicks, cost, and impressions from 1 to 7 days for the keyword identifier given the suggested bid.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219347(v=msads.100).aspx KeywordBidLandscape Data Object
 * 
 * @uses DayMonthAndYear
 * @uses BidLandscapePoint
 * @used-by GetBidLandscapeByKeywordIdsResponse
 */
final class KeywordBidLandscape
{
    /**
     * The keyword identifier.
     *
     * @var int
     */
    public $KeywordId;
    /**
     * The first date used to calculate the bid landscape.
     *
     * @var DayMonthAndYear
     */
    public $StartDate;
    /**
     * The most recent date used to calculate the bid landscape.
     *
     * @var DayMonthAndYear
     */
    public $EndDate;
    /**
     * The list of the total estimated clicks, cost, and impressions from StartDate to EndDate given the suggested bid.
     *
     * @var BidLandscapePoint[]
     */
    public $BidLandscapePoints;
}
