<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * Defines an object that contains a list of search counts for each device and network where the keyword was included in a search query.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219303(v=msads.100).aspx KeywordSearchCount Data Object
 * 
 * @uses SearchCountsByAttributes
 * @used-by GetHistoricalSearchCountResponse
 */
final class KeywordSearchCount
{
    /**
     * The keyword to which the search count data applies.
     *
     * @var string
     */
    public $Keyword;
    /**
     * An array of SearchCountsByAttributes objects that contain search counts for each device and network where the keyword was included in a search query.
     *
     * @var SearchCountsByAttributes[]
     */
    public $SearchCountsByAttributes;
}
