<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

final class Operator
{
    const EQUALS = 'EQUALS';
    const NOT_EQUALS = 'NOT_EQUALS';
    const IN = 'IN';
    const NOT_IN = 'NOT_IN';
    const GREATER_THAN = 'GREATER_THAN';
    const GREATER_THAN_EQUALS = 'GREATER_THAN_EQUALS';
    const LESS_THAN = 'LESS_THAN';
    const LESS_THAN_EQUALS = 'LESS_THAN_EQUALS';
    const STARTS_WITH = 'STARTS_WITH';
    const STARTS_WITH_IGNORE_CASE = 'STARTS_WITH_IGNORE_CASE';
    const CONTAINS = 'CONTAINS';
    const CONTAINS_IGNORE_CASE = 'CONTAINS_IGNORE_CASE';
    const DOES_NOT_CONTAIN = 'DOES_NOT_CONTAIN';
    const DOES_NOT_CONTAIN_IGNORE_CASE = 'DOES_NOT_CONTAIN_IGNORE_CASE';
    const UNKNOWN = 'UNKNOWN';
}
