<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

/**
 * This is the base class from which opportunity objects derive.
 *
 * @link http://msdn.microsoft.com/en-us/library/mt219304(v=msads.100).aspx Opportunity Data Object
 */
class Opportunity
{
    /**
     * An identifier that uniquely identifies the opportunity.
     *
     * @var string
     */
    public $OpportunityKey;
}
