<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */

namespace BingAds\v10\AdInsight;

final class Selector
{
    public $DateRange;
    public $GroupBy;
    public $Ordering;
    public $PageInfo;
    public $Predicates;
    public $SelectedFields;
}
